import turtle
turtle.shape("turtle")
turtle.color("red")
turtle.penup()
turtle.goto(-100, -100)
turtle.pendown()
turtle.left(45)
turtle.forward(50)
turtle.right(65)
turtle.circle(150,350)
#turtle.home()
turtle.right(72)
turtle.forward(50)
turtle.penup()
turtle.goto(-100, -100)
turtle.pendown()
big=("Arial", 36, "normal")
turtle.penup()
turtle.goto(-160,50)
turtle.write("Hello World!", font=big)
turtle.home()
turtle.back(20)
